export const prizes = [
  'Swag Pack',
  'Swag Pack',
  'Swag Pack',
  'Swag Pack',
  'Vive Pro',
  'Swag Pack',
  'Swag Pack',
  'Swag Pack',
  'Swag Pack',
  'Swag Pack',
  'Vive Pro',
  'Swag Pack',
  'Swag Pack',
  'Swag Pack',
  'Swag Pack',
  'Vive Pro + Wireless',
  'Swag Pack',
  'Swag Pack',
  'Swag Pack',
  'Swag Pack',
  'Swag Pack',
  'Vive Pro + Wireless',
]

export const winners = [...[
  'FREEDOM joelseph',
  'AkaRaiden',
  'flasheh',
  'Selfblumpkin',
  'Lambington',
  'JonathanRune',
  'Virt',
  'Dongman',
  'Bri Guy',
  'CyberGeko',
  'ZeroSanity',
  'Elysium',
  'LiamNGNL',
  'LEh4nnes/T.TV',
  'Lana Del Spray',
  'SPONGEQINQINQIN',
  'Dranix',
  'hovopotter',
  'Roffle',
  'Yurie',
  '-----',
  '-----',
].sort((a, b) => a.localeCompare(b))]
